# **EXPLORATORY DATA ANALYSIS**

In [2]:
import pandas as pd

# **CIRCUITS**

In [3]:
df_circuits = pd.read_parquet(r"C:\Users\Asus\Desktop\Formula1\data\bronze\entities\circuits.parquet")
df_circuits.head()

,circuit_ref,circuit_name,city,country,latitude,longitude,altitude_m
0,adelaide,Adelaide Street Circuit,Adelaide,Australia,-34.9272,138.617,None
1,ain-diab,Ain Diab,Casablanca,Morocco,33.5786,-7.6875,None
2,aintree,Aintree,Liverpool,UK,53.4769,-2.94056,None
3,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.968,None
4,americas,Circuit of the Americas,Austin,USA,30.1328,-97.6411,None

- circuit_ref is **PRIMARY KEY**

In [4]:
df_circuits.shape

(78, 7)

In [5]:
len(df_circuits["circuit_ref"].unique())

78

In [6]:
df_circuits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   circuit_ref   78 non-null     object
 1   circuit_name  78 non-null     object
 2   city          78 non-null     object
 3   country       78 non-null     object
 4   latitude      78 non-null     object
 5   longitude     78 non-null     object
 6   altitude_m    0 non-null      object
dtypes: object(7)
memory usage: 4.4+ KB

- changing datatypes of latitude and longitude columns

In [7]:
df_circuits['latitude'] = df_circuits['latitude'].astype(float)
df_circuits['longitude'] = df_circuits['longitude'].astype(float)

- altitude_m column is 100% null - dropping it

In [11]:
df_circuits.drop(columns=["altitude_m"], inplace=True)

In [12]:
df_circuits.head()

,circuit_ref,circuit_name,city,country,latitude,longitude
0,adelaide,Adelaide Street Circuit,Adelaide,Australia,-34.9272,138.61700
1,ain-diab,Ain Diab,Casablanca,Morocco,33.5786,-7.68750
2,aintree,Aintree,Liverpool,UK,53.4769,-2.94056
3,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.96800
4,americas,Circuit of the Americas,Austin,USA,30.1328,-97.64110

In [13]:
df_circuits.to_parquet(r"C:\Users\Asus\Desktop\Formula1\data\silver\entities\cleaned_circuits.parquet")