# **EXPLORATORY DATA ANALYSIS**

In [1]:
import pandas as pd

# **DRIVERS**

In [2]:
df_drivers = pd.read_parquet(
    r'C:\Users\Asus\Desktop\Formula1\data\bronze\entities\drivers.parquet')
df_drivers.head()

,driver_ref,driver_code,driver_number,forename,surname,date_of_birth,nationality
0,abate,None,None,Carlo,Abate,1932-07-10,Italian
1,abecassis,None,None,George,Abecassis,1913-03-21,British
2,acheson,None,None,Kenny,Acheson,1957-11-27,British
3,adams,None,None,Philippe,Adams,1969-11-19,Belgian
4,ader,None,None,Walt,Ader,1913-12-15,American

- 879 unique drivers
- driver_ref is **PRIMARY KEY**

In [3]:
df_drivers.shape # shape of dataset

(879, 7)

In [4]:
len(df_drivers["driver_ref"].unique()) # unique driver_ref

879

In [5]:
df_drivers["driver_name"] = df_drivers["forename"] + " " + df_drivers["surname"] # deriving driver_name column

In [6]:
len(df_drivers["driver_name"].unique()) # unique driver names

879

In [7]:
df_drivers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 879 entries, 0 to 878
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   driver_ref     879 non-null    object
 1   driver_code    107 non-null    object
 2   driver_number  63 non-null     object
 3   forename       879 non-null    object
 4   surname        879 non-null    object
 5   date_of_birth  865 non-null    object
 6   nationality    865 non-null    object
 7   driver_name    879 non-null    object
dtypes: object(8)
memory usage: 55.1+ KB

In [8]:
df_drivers["nationality"].unique()

array(['Italian', 'British', 'Belgian', 'American', 'German', 'Dutch',
       'Thai', 'French', 'Spanish', 'New Zealander', 'Swedish', None,
       'Brazilian', 'Hungarian', 'Danish', 'Monegasque', 'Canadian',
       'Austrian', 'Argentine', 'South African', 'Finnish', 'Australian',
       'Swiss', 'Irish', 'Portuguese', 'Uruguayan', 'Venezuelan',
       'Indian', 'Czech', 'East German', 'Japanese', 'Colombian',
       'Mexican', 'Indonesian', 'Rhodesian', 'Polish', 'Russian',
       'Chilean', 'Malaysian', 'Chinese', 'Liechtensteiner'], dtype=object)

- handling missing values in driver_code column
- driver_code is first three letters of driver's surname

In [9]:
df_drivers[df_drivers["driver_code"].notna()].head()

,driver_ref,driver_code,driver_number,forename,surname,date_of_birth,nationality,driver_name
8,aitken,AIT,89,Jack,Aitken,1995-09-23,British,Jack Aitken
9,albers,ALB,None,Christijan,Albers,1979-04-16,Dutch,Christijan Albers
10,albon,ALB,23,Alexander,Albon,1996-03-23,Thai,Alexander Albon
13,alguersuari,ALG,None,Jaime,Alguersuari,1990-03-23,Spanish,Jaime Alguersuari
16,alonso,ALO,14,Fernando,Alonso,1981-07-29,Spanish,Fernando Alonso

- we have duplicate values in driver_code column

In [10]:
df_drivers["driver_code"] = df_drivers["surname"].str[0:3].str.upper()

- these are the drivers who have missing date of birth and nationality

In [11]:
df_drivers[df_drivers["nationality"].isna()]

,driver_ref,driver_code,driver_number,forename,surname,date_of_birth,nationality,driver_name
31,paul_aron,ARO,None,Paul,Aron,None,None,Paul Aron
62,dino_beganovic,BEG,None,Dino,Beganovic,None,None,Dino Beganovic
124,luke_browning,BRO,None,Luke,Browning,None,None,Luke Browning
187,jak_crawford,CRA,None,Jak,Crawford,None,None,Jak Crawford
217,felipe_drugovich,DRU,None,Felipe,Drugovich,None,None,Felipe Drugovich
221,alexander_dunne,DUN,None,Alexander,Dunne,None,None,Alexander Dunne
277,antonio_fuoco,FUO,None,Antonio,Fuoco,None,None,Antonio Fuoco
361,ryo_hirakawa,HIR,None,Ryo,Hirakawa,None,None,Ryo Hirakawa
384,ayumu_iwasa,IWA,None,Ayumu,Iwasa,None,None,Ayumu Iwasa
445,arthur_leclerc,LEC,None,Arthur,Leclerc,None,None,Arthur Leclerc
497,victor_martins,MAR,None,Victor,Martins,None,None,Victor Martins
564,patricio_o_ward,O'W,None,Patricio,O'Ward,None,None,Patricio O'Ward
715,cian_shields,SHI,None,Cian,Shields,None,None,Cian Shields
792,frederik_vesti,VES,None,Frederik,Vesti,None,None,Frederik Vesti

In [12]:
flagged_drivers = df_drivers[df_drivers["nationality"].isna()]["driver_name"].to_list()

In [13]:
flagged_drivers

['Paul Aron',
 'Dino Beganovic',
 'Luke Browning',
 'Jak Crawford',
 'Felipe Drugovich',
 'Alexander Dunne',
 'Antonio Fuoco',
 'Ryo Hirakawa',
 'Ayumu Iwasa',
 'Arthur Leclerc',
 'Victor Martins',
 "Patricio O'Ward",
 'Cian Shields',
 'Frederik Vesti']

- handling null values in nationality and date_of_birth

In [14]:
driver_data = {
    'Paul Aron':        ('1999-02-04', 'Estonian'),  
    'Dino Beganovic':   ('2004-01-19', 'Swedish'),
    'Luke Browning':    ('2002-01-31', 'British'),
    'Jak Crawford':     ('2005-05-02', 'American'),
    'Felipe Drugovich': ('2000-05-23', 'Brazilian'),
    'Alexander Dunne':  ('2005-11-11', 'Irish'),
    'Antonio Fuoco':    ('1996-05-20', 'Italian'),
    'Ryo Hirakawa':     ('1994-03-07', 'Japanese'),
    'Ayumu Iwasa':      ('2001-09-22', 'Japanese'),
    'Arthur Leclerc':   ('2000-10-14', 'Monégasque'),
    'Victor Martins':   ('2001-06-16', 'French'),
    "Patricio O'Ward":  ('1999-05-06', 'Mexican'),
    'Cian Shields':     ('2005-03-07', 'British'),
    'Frederik Vesti':   ('2002-01-13', 'Danish'),
}

In [15]:
dob_map = df_drivers['driver_name'].map(lambda x: driver_data.get(x, (None, None))[0])
nat_map = df_drivers['driver_name'].map(lambda x: driver_data.get(x, (None, None))[1])

df_drivers['date_of_birth'] = df_drivers['date_of_birth'].fillna(dob_map)
df_drivers['nationality']   = df_drivers['nationality'].fillna(nat_map)

- changing date_of_birth datatype

In [16]:
df_drivers["date_of_birth"] = pd.to_datetime(df_drivers["date_of_birth"])

In [17]:
df_drivers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 879 entries, 0 to 878
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   driver_ref     879 non-null    object
 1   driver_code    879 non-null    object
 2   driver_number  63 non-null     object
 3   forename       879 non-null    object
 4   surname        879 non-null    object
 5   date_of_birth  879 non-null    datetime64[ns]
 6   nationality    879 non-null    object
 7   driver_name    879 non-null    object
dtypes: datetime64[ns](1), object(7)
memory usage: 55.1+ KB

- driver_number column is too sparse - dropping it
- forename and surname columns are redundant now - dropping them

In [18]:
df_drivers.drop(columns=["forename", "surname", "driver_number"], inplace=True)

In [19]:
df_drivers.head()

  driver_ref driver_code date_of_birth nationality       driver_name
0      abate         ABA    1932-07-10     Italian       Carlo Abate
1  abecassis         ABE    1913-03-21     British  George Abecassis
2    acheson         ACH    1957-11-27     British     Kenny Acheson
3      adams         ADA    1969-11-19     Belgian    Philippe Adams
4       ader         ADE    1913-12-15    American         Walt Ader

In [20]:
df_drivers.to_parquet(r"C:\Users\Asus\Desktop\Formula1\data\silver\entities\cleaned_drivers.parquet")