# **EXPLORATORY DATA ANALYSIS**

In [1]:
import pandas as pd

# **SCHEDULE**

In [2]:
df_schedule = pd.read_parquet(r"C:\Users\Asus\Desktop\Formula1\data\bronze\schedule\all_seasons_schedule.parquet")
df_schedule.head()

,season,round_number,race_name,circuit_ref,race_date,race_time,fp1_date,fp2_date,fp3_date,quali_date,sprint_date,has_sprint
0,2018,1,Australian Grand Prix,albert_park,2018-03-25,05:10:00Z,2018-03-23,2018-03-23,2018-03-24,2018-03-24,None,False
1,2018,2,Bahrain Grand Prix,bahrain,2018-04-08,15:10:00Z,2018-04-06,2018-04-06,2018-04-07,2018-04-07,None,False
2,2018,3,Chinese Grand Prix,shanghai,2018-04-15,06:10:00Z,2018-04-13,2018-04-13,2018-04-14,2018-04-14,None,False
3,2018,4,Azerbaijan Grand Prix,baku,2018-04-29,12:10:00Z,2018-04-27,2018-04-27,2018-04-28,2018-04-28,None,False
4,2018,5,Spanish Grand Prix,catalunya,2018-05-13,13:10:00Z,2018-05-11,2018-05-11,2018-05-12,2018-05-12,None,False

- no **PRIMARY KEY**

In [3]:
df_schedule.shape

(173, 12)

In [5]:
len(df_schedule["season"].unique()) # 8 years

8

In [6]:
df_schedule.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173 entries, 0 to 172
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   season        173 non-null    int64
 1   round_number  173 non-null    int64
 2   race_name     173 non-null    object
 3   circuit_ref   173 non-null    object
 4   race_date     173 non-null    object
 5   race_time     173 non-null    object
 6   fp1_date      173 non-null    object
 7   fp2_date      155 non-null    object
 8   fp3_date      149 non-null    object
 9   quali_date    173 non-null    object
 10  sprint_date   24 non-null     object
 11  has_sprint    173 non-null    bool
dtypes: bool(1), int64(2), object(9)
memory usage: 15.2+ KB

- creating **PRIMARY KEY**
- combination of season and round_number columns is unique

In [7]:
df_schedule["schedule_ref"] = df_schedule["season"].astype(str).str[2:4] + "_" + df_schedule["round_number"].astype(str)

In [8]:
len(df_schedule["schedule_ref"].unique())

173

In [9]:
df_schedule["schedule_ref"].nunique()

173

- handling race_time and race_date columns
- combining both the columns meticulously

In [10]:
df_schedule['race_datetime'] = pd.to_datetime(
    df_schedule['race_date'].astype(str) + ' ' + df_schedule['race_time'].astype(str),
    utc=True
)

In [11]:
df_schedule["race_datetime"].head()

0   2018-03-25 05:10:00+00:00
1   2018-04-08 15:10:00+00:00
2   2018-04-15 06:10:00+00:00
3   2018-04-29 12:10:00+00:00
4   2018-05-13 13:10:00+00:00
Name: race_datetime, dtype: datetime64[ns, UTC]

- handling fp2_date, fp3_date and quali_date columns

In [15]:
df_schedule[df_schedule["fp2_date"].isna()].head()

,season,round_number,race_name,circuit_ref,race_date,race_time,fp1_date,fp2_date,fp3_date,quali_date,sprint_date,has_sprint,schedule_ref,race_datetime
106,2023,4,Azerbaijan Grand Prix,baku,2023-04-30,11:00:00Z,2023-04-28,NaT,NaT,2023-04-28,2023-04-29,True,23_4,2023-04-30 11:00:00+00:00
111,2023,9,Austrian Grand Prix,red_bull_ring,2023-07-02,13:00:00Z,2023-06-30,NaT,NaT,2023-06-30,2023-07-01,True,23_9,2023-07-02 13:00:00+00:00
114,2023,12,Belgian Grand Prix,spa,2023-07-30,13:00:00Z,2023-07-28,NaT,NaT,2023-07-28,2023-07-29,True,23_12,2023-07-30 13:00:00+00:00
119,2023,17,Qatar Grand Prix,losail,2023-10-08,17:00:00Z,2023-10-06,NaT,NaT,2023-10-06,2023-10-07,True,23_17,2023-10-08 17:00:00+00:00
120,2023,18,United States Grand Prix,americas,2023-10-22,19:00:00Z,2023-10-20,NaT,NaT,2023-10-20,2023-10-21,True,23_18,2023-10-22 19:00:00+00:00

In [16]:
df_schedule['fp1_date'] = pd.to_datetime(df_schedule['fp1_date'], errors='coerce')
df_schedule['fp2_date'] = pd.to_datetime(df_schedule['fp2_date'], errors='coerce')
df_schedule['fp3_date'] = pd.to_datetime(df_schedule['fp3_date'], errors='coerce')
df_schedule['quali_date'] = pd.to_datetime(df_schedule['quali_date'], errors='coerce')

- removing sprint_date, race_date and race_time column

In [17]:
df_schedule.drop(columns=["race_date", "race_time", "sprint_date"], inplace=True)

In [18]:
df_schedule = df_schedule[["schedule_ref", "season", "round_number", "race_name", "race_datetime", "circuit_ref",
                           "fp1_date", "fp2_date", "fp3_date", "quali_date", "has_sprint"]]

In [19]:
df_schedule.head()

,schedule_ref,season,round_number,race_name,race_datetime,circuit_ref,fp1_date,fp2_date,fp3_date,quali_date,has_sprint
0,18_1,2018,1,Australian Grand Prix,2018-03-25 05:10:00+00:00,albert_park,2018-03-23,2018-03-23,2018-03-24,2018-03-24,False
1,18_2,2018,2,Bahrain Grand Prix,2018-04-08 15:10:00+00:00,bahrain,2018-04-06,2018-04-06,2018-04-07,2018-04-07,False
2,18_3,2018,3,Chinese Grand Prix,2018-04-15 06:10:00+00:00,shanghai,2018-04-13,2018-04-13,2018-04-14,2018-04-14,False
3,18_4,2018,4,Azerbaijan Grand Prix,2018-04-29 12:10:00+00:00,baku,2018-04-27,2018-04-27,2018-04-28,2018-04-28,False
4,18_5,2018,5,Spanish Grand Prix,2018-05-13 13:10:00+00:00,catalunya,2018-05-11,2018-05-11,2018-05-12,2018-05-12,False

In [22]:
df_schedule.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173 entries, 0 to 172
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   schedule_ref   173 non-null    object
 1   season         173 non-null    int64
 2   round_number   173 non-null    int64
 3   race_name      173 non-null    object
 4   race_datetime  173 non-null    datetime64[ns, UTC]
 5   circuit_ref    173 non-null    object
 6   fp1_date       173 non-null    datetime64[ns]
 7   fp2_date       155 non-null    datetime64[ns]
 8   fp3_date       149 non-null    datetime64[ns]
 9   quali_date     173 non-null    datetime64[ns]
 10  has_sprint     173 non-null    bool
dtypes: bool(1), datetime64[ns, UTC](1), datetime64[ns](4), int64(2), object(3)
memory usage: 13.8+ KB

In [23]:
df_schedule.to_parquet(r"C:\Users\Asus\Desktop\Formula1\data\silver\schedule\cleaned_schedule.parquet")